name: Docker Release
on:
  push:
    tags:
      - v*
jobs:
  docker_release:
    name: Publish images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push ceremony creator image to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true     # true to upload image to registry
          tags: iden3/zk-ceremony-create:latest
          target: zk-ceremony-create
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and Push base image to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true     # true to upload image to registry
          tags: iden3/zk-ceremony:latest
          target: zk-ceremony
          cache-from: type=gha
          cache-to: type=gha,mode=max
